services:
  db:
    container_name: database
    image: mysql:8.0
    ports:
      - "3312:3306"
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuserdb
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
  app:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=myuserdb
      - DB_PASSWORD=secret
      - DB_DATABASE=mydb
    depends_on:
      - db

volumes:
  mysql_data:
